"""empty message

Revision ID: 11686fdd4052
Revises: 577c218a6c88
Create Date: 2020-06-20 12:44:50.752630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11686fdd4052'
down_revision = '577c218a6c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=255), nullable=False),
    sa.Column('Q1', sa.Integer(), nullable=True),
    sa.Column('Q2', sa.Integer(), nullable=True),
    sa.Column('Q3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('init_coupon', sa.String(length=255), nullable=True),
    sa.Column('init_coupon_issued_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_subscribing', sa.Boolean(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('churned_at', sa.DateTime(), nullable=True),
    sa.Column('days_passed', sa.Integer(), nullable=True),
    sa.Column('default_time', sa.String(length=255), nullable=True),
    sa.Column('num_of_referrals', sa.Integer(), nullable=True),
    sa.Column('num_of_feedbacks', sa.Integer(), nullable=True),
    sa.Column('enabled_weather', sa.Boolean(), nullable=True),
    sa.Column('enabled_twitter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('line_id')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('line_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('line_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('init_coupon', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('init_coupon_issued_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_subscribing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('subscribed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('churned_at', mysql.DATETIME(), nullable=True),
    sa.Column('days_passed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('default_time', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('num_of_referrals', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('num_of_feedbacks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('enabled_weather', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enabled_twitter', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('line_id', 'user', ['line_id'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('User')
    op.drop_table('Feedback')
    # ### end Alembic commands ###
