"""empty message

Revision ID: 577c218a6c88
Revises: 
Create Date: 2020-06-20 05:48:23.613295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577c218a6c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('init_coupon', sa.String(length=255), nullable=True),
    sa.Column('init_coupon_issued_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_subscribing', sa.Boolean(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('churned_at', sa.DateTime(), nullable=True),
    sa.Column('days_passed', sa.Integer(), nullable=True),
    sa.Column('default_time', sa.String(length=255), nullable=True),
    sa.Column('num_of_referrals', sa.Integer(), nullable=True),
    sa.Column('num_of_feedbacks', sa.Integer(), nullable=True),
    sa.Column('enabled_weather', sa.Boolean(), nullable=True),
    sa.Column('enabled_twitter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
